# fly.toml app configuration file generated for redirection on 2024-01-23T03:16:44+11:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'redirection'
primary_region = 'syd'

[http_service]
  internal_port = 80
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 1024
